version: '3.8'

services:
  traccar:
    build: .
    container_name: traccar
    ports:
      - "8082:8082"
    depends_on:
      - db
    environment:
      - DATABASE_URL=jdbc:mysql://db:3306/traccar
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root

  db:
    image: mysql:8
    container_name: mysql_traccar
    restart: always
    environment:
      MYSQL_DATABASE: traccar
      MYSQL_USER: traccar
      MYSQL_PASSWORD: traccar
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
